name: 'Maven Build'

description: 'Build the platform dependent Java library'

inputs:
  java-version:
    description: 'The Java build version.'
    required: true
    default: '17'

  platform-name:
    description: 'The target platform.'
    required: true

  maven-username:
    description: 'The Maven username.'
    required: true

  maven-password:
    description: 'The Maven password.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up WebRTC cache
      uses: actions/cache@v4
      with:
        path: ~/${{ env.WEBRTC_INSTALL_FOLDER }}
        key: webrtc-${{ env.WEBRTC_CACHE_BRANCH }}-${{ inputs.platform-name }}-${{ hashFiles('webrtc-jni/pom.xml') }}
        restore-keys: webrtc-${{ env.WEBRTC_CACHE_BRANCH }}-${{ inputs.platform-name }}-

    - name: Set up Maven cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-${{ inputs.platform-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-${{ inputs.platform-name }}-

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        architecture: 'x64'
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_TOKEN

    - name: Build
      run: arch -x86_64 mvn package -DskipTests -Pmacos-cross-x86_64
      shell: bash

    - name: Test
      run: arch -x86_64 mvn -B jar:jar surefire:test -Pmacos-cross-x86_64
      shell: bash

    - name: Deploy
      if: ${{ github.event_name != 'pull_request' }}
      env:
        MAVEN_USERNAME: ${{ inputs.maven-username }}
        MAVEN_TOKEN: ${{ inputs.maven-password }}
      run: arch -x86_64 mvn deploy -DskipTests -Pmacos-cross-x86_64
      shell: bash
