/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_VideoDeviceModule */

#ifndef _Included_dev_onvoid_webrtc_media_video_VideoDeviceModule
#define _Included_dev_onvoid_webrtc_media_video_VideoDeviceModule
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceModule
	 * Method:    getCaptureDevices
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceModule_getCaptureDevices
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceModule
	 * Method:    getCaptureCapabilities
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoDevice;)Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceModule_getCaptureCapabilities
	(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
