/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_MediaStream */

#ifndef _Included_dev_onvoid_webrtc_media_MediaStream
#define _Included_dev_onvoid_webrtc_media_MediaStream
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStream
	 * Method:    id
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_dev_onvoid_webrtc_media_MediaStream_id
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStream
	 * Method:    getAudioTracks
	 * Signature: ()[Ldev/onvoid/webrtc/media/audio/AudioTrack;
	 */
	JNIEXPORT jobjectArray JNICALL Java_dev_onvoid_webrtc_media_MediaStream_getAudioTracks
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStream
	 * Method:    getVideoTracks
	 * Signature: ()[Ldev/onvoid/webrtc/media/video/VideoTrack;
	 */
	JNIEXPORT jobjectArray JNICALL Java_dev_onvoid_webrtc_media_MediaStream_getVideoTracks
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStream
	 * Method:    addTrack
	 * Signature: (Ldev/onvoid/webrtc/media/MediaStreamTrack;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStream_addTrack
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStream
	 * Method:    removeTrack
	 * Signature: (Ldev/onvoid/webrtc/media/MediaStreamTrack;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStream_removeTrack
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStream
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStream_dispose
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
