/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_RTCDtlsTransport */

#ifndef _Included_dev_onvoid_webrtc_RTCDtlsTransport
#define _Included_dev_onvoid_webrtc_RTCDtlsTransport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_RTCDtlsTransport
 * Method:    getIceTransport
 * Signature: ()Ldev/onvoid/webrtc/RTCIceTransport;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCDtlsTransport_getIceTransport
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_RTCDtlsTransport
 * Method:    getState
 * Signature: ()Ldev/onvoid/webrtc/RTCDtlsTransportState;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCDtlsTransport_getState
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_RTCDtlsTransport
 * Method:    getRemoteCertificates
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCDtlsTransport_getRemoteCertificates
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_RTCDtlsTransport
 * Method:    registerObserver
 * Signature: (Ldev/onvoid/webrtc/RTCDtlsTransportObserver;)V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCDtlsTransport_registerObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_onvoid_webrtc_RTCDtlsTransport
 * Method:    unregisterObserver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCDtlsTransport_unregisterObserver
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
