/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_desktop_ScreenCapturer */

#ifndef _Included_dev_onvoid_webrtc_media_video_desktop_ScreenCapturer
#define _Included_dev_onvoid_webrtc_media_video_desktop_ScreenCapturer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_ScreenCapturer
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_ScreenCapturer_initialize
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
