/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_RTCRtpTransceiver */

#ifndef _Included_dev_onvoid_webrtc_RTCRtpTransceiver
#define _Included_dev_onvoid_webrtc_RTCRtpTransceiver
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    getMid
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_getMid
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    getSender
	 * Signature: ()Ldev/onvoid/webrtc/RTCRtpSender;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_getSender
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    getReceiver
	 * Signature: ()Ldev/onvoid/webrtc/RTCRtpReceiver;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_getReceiver
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    getDirection
	 * Signature: ()Ldev/onvoid/webrtc/RTCRtpTransceiverDirection;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_getDirection
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    setDirection
	 * Signature: (Ldev/onvoid/webrtc/RTCRtpTransceiverDirection;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_setDirection
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    getCurrentDirection
	 * Signature: ()Ldev/onvoid/webrtc/RTCRtpTransceiverDirection;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_getCurrentDirection
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    stop
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_stop
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    stopped
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_stopped
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    getCodecPreferences
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_getCodecPreferences
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpTransceiver
	 * Method:    setCodecPreferences
	 * Signature: (Ljava/util/List;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpTransceiver_setCodecPreferences
	(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
