/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_VideoTrack */

#ifndef _Included_dev_onvoid_webrtc_media_video_VideoTrack
#define _Included_dev_onvoid_webrtc_media_video_VideoTrack
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoTrack
	 * Method:    addSinkInternal
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoTrackSink;)J
	 */
	JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_video_VideoTrack_addSinkInternal
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoTrack
	 * Method:    removeSinkInternal
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoTrack_removeSinkInternal
	(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
