/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_logging_Logging */

#ifndef _Included_dev_onvoid_webrtc_logging_Logging
#define _Included_dev_onvoid_webrtc_logging_Logging
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_logging_Logging
	 * Method:    addLogSink
	 * Signature: (Ldev/onvoid/webrtc/logging/Logging/Severity;Ldev/onvoid/webrtc/logging/LogSink;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_logging_Logging_addLogSink
	(JNIEnv *, jclass, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_logging_Logging
	 * Method:    log
	 * Signature: (Ldev/onvoid/webrtc/logging/Logging/Severity;Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_logging_Logging_log
	(JNIEnv *, jclass, jobject, jstring);

	/*
	 * Class:     dev_onvoid_webrtc_logging_Logging
	 * Method:    logToDebug
	 * Signature: (Ldev/onvoid/webrtc/logging/Logging/Severity;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_logging_Logging_logToDebug
	(JNIEnv *, jclass, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_logging_Logging
	 * Method:    logThreads
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_logging_Logging_logThreads
	(JNIEnv *, jclass, jboolean);

	/*
	 * Class:     dev_onvoid_webrtc_logging_Logging
	 * Method:    logTimestamps
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_logging_Logging_logTimestamps
	(JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
