name: 'Prepare Linux Build'

description: 'Frees up disk space and installs required packages for Linux builds.'

runs:
  using: "composite"
  steps:
    - name: Disk cleanup
      run: |
        set -x
        df -h
        #sudo du -h -d1 /usr/local
        #sudo du -h -d1 /usr/local/share
        #sudo du -h -d1 /usr/local/lib
        #sudo du -h -d1 /usr/share
        RMI=`docker images -q -a`
        if [ -n "$RMI" ]; then
          docker rmi $RMI
        fi
        # 4.6G
        sudo rm -rf /usr/local/.ghcup
        # 1.7G
        sudo rm -rf /usr/share/swift
        # 1.4G
        sudo rm -rf /usr/share/dotnet
        # 13G
        sudo rm -rf /usr/local/lib/android
        df -h
      shell: bash

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y pulseaudio libpulse-dev libasound2-dev libdbus-1-dev libudev-dev libv4l-dev libx11-dev libxcomposite-dev libxrandr-dev libxfixes-dev binutils cmake git locales lsb-release ninja-build pkg-config python3 python3-setuptools rsync unzip wget xz-utils

        # More recent LLVM and Clang.
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.llvm }} all

        # Required for testing
        #pulseaudio --start
        sudo apt-get install -y pipewire pipewire-pulse gstreamer1.0-pipewire libspa-0.2-bluetooth libspa-0.2-jack pipewire-audio-client-libraries
        systemctl --user daemon-reload
        systemctl --user --now enable pipewire{,-pulse}.{socket,service}
      shell: bash
