name: 'Prepare macOS Build'

description: 'Installs required packages for macOS builds.'

runs:
  using: "composite"
  steps:
    - name: Install required packages
      run: |
        # Required on macos-14
        brew install python-setuptools
      shell: bash

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
      shell: bash
