/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioTrackSource */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioTrackSource
#define _Included_dev_onvoid_webrtc_media_audio_AudioTrackSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioTrackSource
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioTrackSource_dispose
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
