/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_CustomVideoSource */

#ifndef _Included_dev_onvoid_webrtc_media_video_CustomVideoSource
#define _Included_dev_onvoid_webrtc_media_video_CustomVideoSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_CustomVideoSource
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_CustomVideoSource_initialize
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_CustomVideoSource
	 * Method:    initializeWithClock
	 * Signature: (Ldev/onvoid/webrtc/media/SyncClock;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_CustomVideoSource_initializeWithClock
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_CustomVideoSource
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_CustomVideoSource_dispose
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_CustomVideoSource
	 * Method:    pushFrame
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoFrame;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_CustomVideoSource_pushFrame
	(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif