/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_desktop_DesktopCapturer */

#ifndef _Included_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
#define _Included_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
	 * Method:    getDesktopSources
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer_getDesktopSources
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
	 * Method:    selectSource
	 * Signature: (Ldev/onvoid/webrtc/media/video/desktop/DesktopSource;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer_selectSource
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
	 * Method:    setFocusSelectedSource
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer_setFocusSelectedSource
	(JNIEnv*, jobject, jboolean);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
	 * Method:    start
	 * Signature: (Ldev/onvoid/webrtc/media/video/desktop/DesktopCaptureCallback;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer_start
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_desktop_DesktopCapturer
	 * Method:    captureFrame
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_DesktopCapturer_captureFrame
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
