/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioDeviceModule */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioDeviceModule
#define _Included_dev_onvoid_webrtc_media_audio_AudioDeviceModule
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    initPlayout
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_initPlayout
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    stopPlayout
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_stopPlayout
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    startPlayout
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_startPlayout
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    initRecording
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_initRecording
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    stopRecording
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_stopRecording
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    startRecording
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_startRecording
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getPlayoutDevices
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getPlayoutDevices
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getRecordingDevices
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getRecordingDevices
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    setPlayoutDevice
	 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioDevice;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_setPlayoutDevice
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    setRecordingDevice
	 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioDevice;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_setRecordingDevice
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    isSpeakerMuted
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_isSpeakerMuted
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    isMicrophoneMuted
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_isMicrophoneMuted
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getSpeakerVolume
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getSpeakerVolume
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getMaxSpeakerVolume
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getMaxSpeakerVolume
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getMinSpeakerVolume
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getMinSpeakerVolume
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getMicrophoneVolume
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getMicrophoneVolume
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getMaxMicrophoneVolume
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getMaxMicrophoneVolume
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    getMinMicrophoneVolume
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_getMinMicrophoneVolume
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    setSpeakerVolume
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_setSpeakerVolume
	(JNIEnv *, jobject, jint);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    setSpeakerMute
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_setSpeakerMute
	(JNIEnv *, jobject, jboolean);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    setMicrophoneVolume
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_setMicrophoneVolume
	(JNIEnv *, jobject, jint);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    setMicrophoneMute
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_setMicrophoneMute
	(JNIEnv *, jobject, jboolean);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    addSinkInternal
	 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioSink;)J
	 */
	JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_addSinkInternal
	(JNIEnv*, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    removeSinkInternal
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_removeSinkInternal
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    addSourceInternal
	 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioSource;)J
	 */
	JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_addSourceInternal
	(JNIEnv*, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    removeSourceInternal
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_removeSourceInternal
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    disposeInternal
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_disposeInternal
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_initialize
	(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
