/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_desktop_ScreenSaver */

#ifndef _Included_dev_onvoid_webrtc_media_video_desktop_ScreenSaver
#define _Included_dev_onvoid_webrtc_media_video_desktop_ScreenSaver
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     dev_onvoid_webrtc_media_video_desktop_ScreenSaver
     * Method:    inhibit
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_PowerManagement_enableUserActivity
      (JNIEnv *, jobject);

    /*
     * Class:     dev_onvoid_webrtc_media_video_desktop_ScreenSaver
     * Method:    uninhibit
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_desktop_PowerManagement_disableUserActivity
      (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
