/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_ProcessingConfig */

#ifndef _Included_dev_onvoid_webrtc_media_audio_ProcessingConfig
#define _Included_dev_onvoid_webrtc_media_audio_ProcessingConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_media_audio_ProcessingConfig
 * Method:    setProcessingConfig
 * Signature: (Ldev/onvoid/webrtc/media/audio/StreamName;Ldev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;)V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_ProcessingConfig_setProcessingConfig
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_ProcessingConfig
 * Method:    getProcessingConfig
 * Signature: (Ldev/onvoid/webrtc/media/audio/StreamName;)Ldev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_audio_ProcessingConfig_getProcessingConfig
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
