/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioTrackSource */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioTrackSource
#define _Included_dev_onvoid_webrtc_media_audio_AudioTrackSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioTrackSource
 * Method:    addSinkInternal
 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioTrackSink;)J
 */
JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_audio_AudioTrackSource_addSinkInternal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioTrackSource
 * Method:    removeSinkInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioTrackSource_removeSinkInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioTrackSource
 * Method:    setVolume
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioTrackSource_setVolume
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
