/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioDecoderFactory */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioDecoderFactory
#define _Included_dev_onvoid_webrtc_media_audio_AudioDecoderFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioDecoderFactory
 * Method:    getSupportedDecoders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDecoderFactory_getSupportedDecoders
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioDecoderFactory
 * Method:    isSupportedDecoder
 * Signature: (Ldev/onvoid/webrtc/media/audio/SdpAudioFormat;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDecoderFactory_isSupportedDecoder
  (JNIEnv *, jobject, jobject);


#ifdef __cplusplus
}
#endif
#endif
