/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_VideoBufferConverter */

#ifndef _Included_dev_onvoid_webrtc_media_video_VideoBufferConverter
#define _Included_dev_onvoid_webrtc_media_video_VideoBufferConverter
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoBufferConverter
	 * Method:    I420toByteArray
	 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I[BIII)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoBufferConverter_I420toByteArray
	(JNIEnv *, jclass, jobject, jint, jobject, jint, jobject, jint, jbyteArray, jint, jint, jint);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoBufferConverter
	 * Method:    I420toDirectBuffer
	 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;III)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoBufferConverter_I420toDirectBuffer
	(JNIEnv *, jclass, jobject, jint, jobject, jint, jobject, jint, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
