/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioResampler */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioResampler
#define _Included_dev_onvoid_webrtc_media_audio_AudioResampler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioResampler
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioResampler_dispose
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioResampler
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioResampler_initialize
	(JNIEnv*, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioResampler
	 * Method:    resetInternal
	 * Signature: (III)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioResampler_resetInternal
	(JNIEnv*, jobject, jint, jint, jint);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioResampler
	 * Method:    resampleInternal
	 * Signature: ([BI[BI)I
	 */
	JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioResampler_resampleInternal
	(JNIEnv*, jobject, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
