/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_VideoDeviceSource */

#ifndef _Included_dev_onvoid_webrtc_media_video_VideoDeviceSource
#define _Included_dev_onvoid_webrtc_media_video_VideoDeviceSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceSource
	 * Method:    setVideoCaptureDevice
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoDevice;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceSource_setVideoCaptureDevice
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceSource
	 * Method:    setVideoCaptureCapability
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoCaptureCapability;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceSource_setVideoCaptureCapability
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceSource
	 * Method:    start
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceSource_start
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceSource
	 * Method:    stop
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceSource_stop
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceSource
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceSource_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoDeviceSource
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoDeviceSource_initialize
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
