/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioEncoderFactory */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioEncoderFactory
#define _Included_dev_onvoid_webrtc_media_audio_AudioEncoderFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioEncoderFactory
 * Method:    getSupportedEncoders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_audio_AudioEncoderFactory_getSupportedEncoders
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioEncoderFactory
 * Method:    queryAudioEncoder
 * Signature: (Ldev/onvoid/webrtc/media/audio/SdpAudioFormat;)Ldev/onvoid/webrtc/media/audio/AudioCodecInfo;
 */
JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_audio_AudioEncoderFactory_queryAudioEncoder
  (JNIEnv *, jobject, jobject);


#ifdef __cplusplus
}
#endif
#endif
