/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_video_VideoCapture */

#ifndef _Included_dev_onvoid_webrtc_media_video_VideoCapture
#define _Included_dev_onvoid_webrtc_media_video_VideoCapture
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    setVideoCaptureDevice
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoDevice;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_setVideoCaptureDevice
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    setVideoCaptureCapability
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoCaptureCapability;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_setVideoCaptureCapability
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    setVideoSink
	 * Signature: (Ldev/onvoid/webrtc/media/video/VideoTrackSink;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_setVideoSink
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    start
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_start
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    stop
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_stop
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_video_VideoCapture
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_video_VideoCapture_initialize
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
