/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_RTCRtpReceiver */

#ifndef _Included_dev_onvoid_webrtc_RTCRtpReceiver
#define _Included_dev_onvoid_webrtc_RTCRtpReceiver
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    getTrack
	 * Signature: ()Ldev/onvoid/webrtc/media/MediaStreamTrack;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_getTrack
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    getTransport
	 * Signature: ()Ldev/onvoid/webrtc/RTCDtlsTransport;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_getTransport
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    getParameters
	 * Signature: ()Ldev/onvoid/webrtc/RTCRtpParameters;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_getParameters
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    getContributingSources
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_getContributingSources
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    getSynchronizationSources
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_getSynchronizationSources
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    setTransform
	 * Signature: (Ldev/onvoid/webrtc/RTCEncodedFrameTransformer;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_setTransform
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    requestKeyFrame
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_requestKeyFrame
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    getId
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_getId
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    setObserver
	 * Signature: (Ldev/onvoid/webrtc/RTCRtpReceiverObserver;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_setObserver
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpReceiver
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpReceiver_dispose
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
