/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_SyncClock */

#ifndef _Included_dev_onvoid_webrtc_media_SyncClock
#define _Included_dev_onvoid_webrtc_media_SyncClock
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_SyncClock
	 * Method:    getTimestampUs
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_SyncClock_getTimestampUs
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_SyncClock
	 * Method:    getTimestampMs
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_SyncClock_getTimestampMs
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_SyncClock
	 * Method:    getNtpTime
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_dev_onvoid_webrtc_media_SyncClock_getNtpTime
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_SyncClock
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_SyncClock_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_SyncClock
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_SyncClock_initialize
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif