/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_MediaStreamTrack */

#ifndef _Included_dev_onvoid_webrtc_media_MediaStreamTrack
#define _Included_dev_onvoid_webrtc_media_MediaStreamTrack
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_dispose
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    getKind
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_getKind
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    getId
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_getId
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    isEnabled
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_isEnabled
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    setEnabled
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_setEnabled
	(JNIEnv *, jobject, jboolean);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    getState
	 * Signature: ()Ldev/onvoid/webrtc/media/MediaStreamTrackState;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_getState
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    addEndedEventListener
	 * Signature: (Ljava/lang/Runnable;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_addEndedEventListener
	(JNIEnv*, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    removeEndedEventListener
	 * Signature: (Ljava/lang/Runnable;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_removeEndedEventListener
	(JNIEnv*, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    addMuteEventListener
	 * Signature: (Ljava/util/function/Consumer;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_addMuteEventListener
	(JNIEnv*, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_MediaStreamTrack
	 * Method:    removeMuteEventListener
	 * Signature: (Ljava/util/function/Consumer;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_MediaStreamTrack_removeMuteEventListener
	(JNIEnv*, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
