/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_CustomAudioSource */

#ifndef _Included_dev_onvoid_webrtc_media_audio_CustomAudioSource
#define _Included_dev_onvoid_webrtc_media_audio_CustomAudioSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_audio_CustomAudioSource
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_CustomAudioSource_initialize
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_CustomAudioSource
	 * Method:    pushAudio
	 * Signature: ([BIIII)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_CustomAudioSource_pushAudio
	(JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif