/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioProcessing */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioProcessing
#define _Included_dev_onvoid_webrtc_media_audio_AudioProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    applyConfig
 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioProcessingConfig;)V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_applyConfig
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    ProcessStream
 * Signature: ([SLdev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;Ldev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;[S)I
 */
JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_ProcessStream___3SLdev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2Ldev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2_3S
  (JNIEnv *, jobject, jshortArray, jobject, jobject, jshortArray);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    ProcessStream
 * Signature: ([FLdev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;Ldev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;[F)I
 */
JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_ProcessStream___3FLdev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2Ldev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2_3F
  (JNIEnv *, jobject, jfloatArray, jobject, jobject, jfloatArray);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    ProcessReverseStream
 * Signature: ([SLdev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;Ldev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;[S)I
 */
JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_ProcessReverseStream___3SLdev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2Ldev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2_3S
  (JNIEnv *, jobject, jshortArray, jobject, jobject, jshortArray);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    ProcessReverseStream
 * Signature: ([FLdev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;Ldev/onvoid/webrtc/media/audio/AudioProcessingStreamConfig;[F)I
 */
JNIEXPORT jint JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_ProcessReverseStream___3FLdev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2Ldev_onvoid_webrtc_media_audio_AudioProcessingStreamConfig_2_3F
  (JNIEnv *, jobject, jfloatArray, jobject, jobject, jfloatArray);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_dispose
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_initialize
  (JNIEnv *, jobject);

/*
 * Class:     dev_onvoid_webrtc_media_audio_AudioProcessing
 * Method:    updateStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioProcessing_updateStats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
