/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_MediaSource */

#ifndef _Included_dev_onvoid_webrtc_media_MediaSource
#define _Included_dev_onvoid_webrtc_media_MediaSource
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_MediaSource
	 * Method:    getState
	 * Signature: ()Ldev/onvoid/webrtc/media/MediaSource/State;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_media_MediaSource_getState
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
