/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_HeadlessAudioDeviceModule */

#ifndef _Included_dev_onvoid_webrtc_media_audio_HeadlessAudioDeviceModule
#define _Included_dev_onvoid_webrtc_media_audio_HeadlessAudioDeviceModule
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 * Class:     dev_onvoid_webrtc_media_audio_HeadlessAudioDeviceModule
	 * Method:    initialize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_HeadlessAudioDeviceModule_initialize
	  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
