/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_codec_BuiltinAudioDecoderFactory */

#ifndef _Included_dev_onvoid_webrtc_media_audio_codec_BuiltinAudioDecoderFactory
#define _Included_dev_onvoid_webrtc_media_audio_codec_BuiltinAudioDecoderFactory
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_audio_codec_BuiltinAudioDecoderFactory
	 * Method:    getBuiltinCodecs
	 * Signature: ()[Ldev/onvoid/webrtc/media/audio/codec/AudioCodecInfo;
	 */
	JNIEXPORT jobjectArray JNICALL Java_dev_onvoid_webrtc_media_audio_codec_BuiltinAudioDecoderFactory_getBuiltinCodecs
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
