/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_RTCRtpSender */

#ifndef _Included_dev_onvoid_webrtc_RTCRtpSender
#define _Included_dev_onvoid_webrtc_RTCRtpSender
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    getTrack
	 * Signature: ()Ldev/onvoid/webrtc/media/MediaStreamTrack;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_getTrack
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    getTransport
	 * Signature: ()Ldev/onvoid/webrtc/RTCDtlsTransport;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_getTransport
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    replaceTrack
	 * Signature: (Ldev/onvoid/webrtc/media/MediaStreamTrack;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_replaceTrack
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    setParameters
	 * Signature: (Ldev/onvoid/webrtc/RTCRtpSendParameters;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_setParameters
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    getParameters
	 * Signature: ()Ldev/onvoid/webrtc/RTCRtpSendParameters;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_getParameters
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    setStreams
	 * Signature: (Ljava/util/List;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_setStreams
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    getDtmfSender
	 * Signature: ()Ldev/onvoid/webrtc/RTCDtmfSender;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_getDtmfSender
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    setTransform
	 * Signature: (Ldev/onvoid/webrtc/RTCEncodedFrameTransformer;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_setTransform
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    generateKeyFrame
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_generateKeyFrame
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    getId
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_getId
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    setObserver
	 * Signature: (Ldev/onvoid/webrtc/RTCRtpSenderObserver;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_setObserver
	(JNIEnv *, jobject, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    getStreams
	 * Signature: ()Ljava/util/List;
	 */
	JNIEXPORT jobject JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_getStreams
	(JNIEnv *, jobject);

	/*
	 * Class:     dev_onvoid_webrtc_RTCRtpSender
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_RTCRtpSender_dispose
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
