/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_onvoid_webrtc_media_audio_AudioDeviceModule */

#ifndef _Included_dev_onvoid_webrtc_media_audio_AudioDeviceModule
#define _Included_dev_onvoid_webrtc_media_audio_AudioDeviceModule
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_onvoid_webrtc_media_audio_AudioDeviceModule
	 * Method:    initialize
	 * Signature: (Ldev/onvoid/webrtc/media/audio/AudioLayer;)V
	 */
	JNIEXPORT void JNICALL Java_dev_onvoid_webrtc_media_audio_AudioDeviceModule_initialize
	(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
